# Numpy Exercise

#### 1. Import the numpy package under the name  (★☆☆)

In [0]:
import numpy as np

#### 2. Print the numpy version and the configuration  (★☆☆)

In [0]:
print(np.__version__)

1.17.4


#### 3. Create a null vector of size 10 (★☆☆)

In [0]:
arr = np.zeros(10)

#### 4.  How to find the memory size of any array (★☆☆)

In [0]:
print(arr.size)

10


#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆)

In [0]:
np.add?

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [0]:
ar = np.zeros(10)
ar[4]=1

#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆)

In [0]:
random1049 = np.arange(10,49)
print(random1049)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


#### 8.  Reverse a vector (first element becomes last) (★☆☆)

In [0]:
rev = random1049[::-1]
print(rev)

[48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26 25
 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [0]:
array9 = np.arange(0,9).reshape(3,3)
print(array9)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆)

In [0]:
arr10 = [1,2,0,0,4,0]
np.nonzero(arr10)

(array([0, 1, 4]),)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [0]:
arr11 = np.identity(3)
print(arr11)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [0]:
arr12 = np.random.random((3,3,3))
print(arr12)

[[[0.37311841 0.53768221 0.28037749]
  [0.62066601 0.80248025 0.71609593]
  [0.6839484  0.96457489 0.57510855]]

 [[0.7283903  0.69683607 0.71178636]
  [0.11185444 0.6237962  0.92988637]
  [0.58646031 0.34936965 0.9547647 ]]

 [[0.83738088 0.21614324 0.53999892]
  [0.10399398 0.64852576 0.4403252 ]
  [0.91637461 0.66896375 0.61070556]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [0]:
arr13 = np.random.random((10,10))
print(arr13)
arr13min = arr13.min()
arr13max = arr13.max()
print(arr13min)
print(arr13max)

[[9.15008539e-01 6.36111421e-01 8.49344037e-01 4.67513277e-01
  9.93332854e-01 1.27452934e-01 3.32618119e-01 8.57570807e-01
  3.74724042e-01 2.94026779e-01]
 [4.09347873e-02 9.45064395e-01 6.74299645e-01 1.12247637e-01
  5.57186160e-01 5.01269264e-02 6.00958389e-01 6.24585756e-01
  2.00329404e-01 3.87007941e-02]
 [8.94974519e-01 4.00138431e-01 4.33881203e-01 9.61026460e-01
  5.10231214e-01 5.15436340e-02 1.18340427e-01 1.45334387e-02
  4.38589960e-02 3.62881962e-01]
 [2.14405315e-01 5.62799102e-01 7.89883159e-01 8.17558961e-01
  4.41394113e-01 5.31258423e-01 8.29266997e-01 2.92681513e-01
  7.10477121e-01 7.22750538e-01]
 [8.60762212e-01 2.09961735e-01 7.56370825e-01 8.71765685e-02
  5.90993189e-03 1.71239008e-01 7.23017482e-01 1.32298529e-01
  8.05649539e-01 8.01912022e-01]
 [9.20534294e-01 2.17863059e-03 5.63899306e-01 4.15338229e-01
  6.84583968e-01 8.12589778e-01 7.26775534e-01 5.75837249e-01
  3.36578913e-01 9.89122504e-01]
 [8.56481484e-01 9.13941171e-02 2.89882255e-01 9.05756485e

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [0]:
arr14 = np.random.random(30)
print(arr14)
print(arr14.mean())

[0.13993007 0.97383907 0.79704131 0.09641229 0.27753915 0.79730829
 0.56525379 0.41102615 0.63968589 0.71529296 0.99894708 0.73557897
 0.001397   0.23380812 0.87305289 0.4896458  0.51803673 0.3619878
 0.01183259 0.81940352 0.19422824 0.71498891 0.078545   0.92807405
 0.00613044 0.2785151  0.25291343 0.08701493 0.49208752 0.6477772 ]
0.4712431432562998


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [0]:
arr15 = np.ones((5,5))
arr15[1:-1,1:-1] = 0
print(arr15)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [0]:
arr16 = np.ones((10,10))
arr16 = np.pad(arr16, pad_width=1, mode='constant', constant_values=0)
print(arr16)
np.pad?

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [0]:
#False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [0]:
Z = np.diag(np.arange(1,5), k = -1)
print (Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [0]:
Z = np.zeros ((8,8), dtype=int)
Z[1::2, ::2]= 1
Z[::2, 1::2] = 1
print (Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [0]:
print (np.unravel_index(100, (6,7,8)))

(1, 5, 4)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [0]:
array= np.array([[0,1], [1,0]])
Z = np.tile(array,(4,4))
print (Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [0]:
Z = np.random.random((5,5))
Zmax, Zmin = Z.max(), Z.min()
Z= (Z-Zmin)/(Zmax-Zmin)
print (Z)

[[0.76144432 0.7122652  0.54337976 0.70944529 0.10880043]
 [0.78766872 0.51632008 0.33126566 0.30017734 0.76775428]
 [0.65080399 0.11486191 0.30340567 0.1115561  0.97074541]
 [0.         0.18374901 0.99690486 0.88309494 0.31004185]
 [0.85125535 0.78512064 1.         0.77886018 0.6800843 ]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [0]:
color = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:4: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  after removing the cwd from sys.path.


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [0]:
x = np.arange(15).reshape((5, 3))
y = np.arange(6).reshape((3, 2))
np.dot(x, y)


array([[ 10,  13],
       [ 28,  40],
       [ 46,  67],
       [ 64,  94],
       [ 82, 121]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [0]:
x = np.arange(11)
x[(x >= 3) & (x <= 8)] = -1
print(x)

[ 0  1  2 -1 -1 -1 -1 -1 -1  9 10]


#### 26. What is the output of the following script? (★☆☆)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [0]:
9
10

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [0]:
#Z ** Z       # = [0^0, 1^1, 2^2] = [1, 1, 4]
#2 << Z >> 2  # = [0, 1, 2]
#Z < - Z      # = [False, False, False]
#1j * Z       # = [0 + 0.j, 0 + 1.j, 0 + 2.j]
#Z / 1 / 1    # = [0, 1, 2]
#Z < Z > Z    # ValueError

#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [0]:
#[-9.22337204e+18]
#/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
 # """Entry point for launching an IPython kernel.
#/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in floor_divide


[-9.22337204e+18]


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  


#### 29. How to round away from zero a float array ? (★☆☆)

In [0]:
x = np.random.uniform(-10, +10, 10)
np.copysign(np.ceil(np.abs(x)), x)

array([  9.,  -9.,  -5.,  -1.,  -6.,  10.,  -4.,  -5.,  -3., -10.])

#### 30. How to find common values between two arrays? (★☆☆)

In [0]:
x = np.arange(0, 10)
y = np.arange(5, 15)
print(np.intersect1d(x, y))

[5 6 7 8 9]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [0]:
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0

# Back to sanity
_ = np.seterr(**defaults)


#### 32. Is the following expressions true? (★☆☆)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [0]:
#False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [0]:
today = np.datetime64('today', 'D')
yesterday = today - np.datetime64(1, 'D')
tomorrow = today + np.datetime64(1, 'D')


UFuncTypeError: ignored

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [0]:
x = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(x)


['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆)

In [0]:
A = np.ones(3) * 1
B = np.ones(3) * 2
C = np.ones(3) * 3
np.add(A, B, out=B)
np.divide(A, 2, out=A)
np.negative(A, out=A)
np.multiply(A, B, out=A)

[2. 2. 2.]
[3. 3. 3.]


array([-1.5, -1.5, -1.5])

#### 36. Extract the integer part of a random array using 5 different methods (★★☆)

In [0]:
x = np.random.uniform(-10, +10, 10)
x.astype(np.int32)
np.trunc(x)


array([-9., -6.,  2.,  0., -8., -8.,  2., -4.,  6.,  6.])

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [0]:
x = np.zeros((5, 5))
x += np.arange(5)
print(x)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [0]:
def generate_integers():
    for i in range(10):
        yield i
np.fromiter(generate_integers(), dtype=np.float32, count=-1)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float32)

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [0]:
print(np.linspace(start=0, stop=11, num=10, endpoint = False))

[0.  1.1 2.2 3.3 4.4 5.5 6.6 7.7 8.8 9.9]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [0]:
x = np.random.random(size=10)
x.sort()
print(x)

[0.14794878 0.15559436 0.37406658 0.5737473  0.62460532 0.75074528
 0.80713008 0.85383654 0.89786689 0.9585651 ]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [0]:
import time

begin_time = time.time()
x = np.arange(1000000)
np.sum(x)
end_time = time.time()
print(str(1000*(end_time - begin_time)))

begin_time2 = time.time()
x = np.arange(1000000)
np.add.reduce(x)
end_time2 = time.time()
print(str(1000*(end_time2 - begin_time2)))

13.742208480834961
8.305549621582031


#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [0]:
A = np.arange(10)
B = np.arange(10)
np.array_equal(A, B)

True

#### 43. Make an array immutable (read-only) (★★☆)

In [0]:
x = np.zeros(10)
x.flags.writeable = False

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [0]:
Z = np.random.random((10, 2))
X, Y = Z[:, 0], Z[:, 1]
R = np.sqrt(X ** 2 + Y ** 2)
T = np.arctan2(Y, X)
print(R)
print(T)

[0.79961469 0.73572735 0.51703958 0.70200239 1.19350023 0.67777948
 0.68548933 0.42912436 0.78238099 0.41737916]
[0.82295126 0.18727679 0.38142451 0.83850093 0.94031127 1.10582778
 0.27544048 0.82835655 1.17267077 0.38437541]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [6]:
x = np.random.random(10)
print(x)
x[x == np.max(x)] = 0
print(x)
x[x.argmax()] = 0
print(x)

[0.93629648 0.85957326 0.13497129 0.26338154 0.08811165 0.70122142
 0.83444991 0.64738049 0.79871531 0.30975028]
[0.         0.85957326 0.13497129 0.26338154 0.08811165 0.70122142
 0.83444991 0.64738049 0.79871531 0.30975028]
[0.         0.         0.13497129 0.26338154 0.08811165 0.70122142
 0.83444991 0.64738049 0.79871531 0.30975028]


#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆)

In [18]:
z = np.zeros((5, 5), [('x', float), ('y', float)])
print(z)
z['x'], z['y'] = np.meshgrid(np.linspace(0, 1, 5), np.linspace(0, 1, 5))
print(z)


[[(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]]
[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

In [26]:
x = np.random.random((5, 5))
y = np.random.random((5, 5))
print(x)
print(y)
c = 1 / (x - y)
c = 1 / np.subtract(x, y)
print(c)
print(np.linalg.det(c))

[[0.3887157  0.01737252 0.11508338 0.19493091 0.56615148]
 [0.8982466  0.06410909 0.6075324  0.21913413 0.4571111 ]
 [0.47716443 0.78762034 0.64470695 0.86191163 0.30215988]
 [0.3938938  0.81494695 0.61559001 0.27696525 0.41987731]
 [0.26700171 0.35021671 0.38765343 0.16512182 0.40428679]]
[[0.76827109 0.9540219  0.39629444 0.26283246 0.85531095]
 [0.43257395 0.93824892 0.26703068 0.26595122 0.83789793]
 [0.52852575 0.13329807 0.58403641 0.02343835 0.77695865]
 [0.11770944 0.88299823 0.40538674 0.95448066 0.73143361]
 [0.12860904 0.44553438 0.00247182 0.92962436 0.59943643]]
[[ -2.63466156  -1.06763536  -3.55604795 -14.72720491  -3.45829921]
 [  2.14743127  -1.14398173   2.93684273 -21.35972098  -2.62614119]
 [-19.46990511   1.52829889  16.48246503   1.19264386  -2.10615544]
 [  3.62076982 -14.69479953   4.75730001  -1.47598119  -3.20969281]
 [  7.22581607 -10.4912342    2.59617789  -1.30804014  -5.12427275]]
-211928.39885514995


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [27]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆)

In [29]:
Z = np.zeros((5,5))
print(Z)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [32]:
Z = np.arange(100)
print(Z)
v = np.random.uniform(0,100)
print(v)
index = (np.abs(Z-v)).argmin()
print(Z[index])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
63.079457700127136
63


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

#### 54. How to read the following file? (★★☆)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)